import 'package:cloud_firestore/cloud_firestore.dart';

class Lottery {
  final String id;

  final String title;
  final String description;
  final String? imageUrl;

  final double jackpot;
  final double pricePerTicket;

 final int totalTickets;
final int ticketsSold;
final int remainingTickets;
final int maxTicketsPerUser;

  final String category;
  final String cardStyle;
  final String lotteryType;

  final String? drawFrequency;
  final bool isPublic;

  final DateTime? nextDrawAt;

  final String status;

  final String creatorId;
  final String creatorName;
  final DateTime createdAt;

  // HOME CARD DISPLAY
  final double progress;
  final int themeColor;

  // ==============================
  // DRAW SYSTEM
  // ==============================

  final int numberOfWinners;

  // IDs of the users who won
  final List<String> winnerIds;

  // Actual ticket numbers that won
  final List<int> winningTicketNumbers;

  // Message generated by the draw system
  final String? resultMessage;

  // Time the draw was completed
  final DateTime? drawCompletedAt;

  Lottery({
    required this.id,

    required this.title,
    required this.description,
    this.imageUrl,

    required this.jackpot,
    required this.pricePerTicket,

    required this.totalTickets,
    required this.ticketsSold,
    required this.remainingTickets,
    required this.maxTicketsPerUser,

    required this.category,
    required this.cardStyle,
    required this.lotteryType,

    this.drawFrequency,
    required this.isPublic,

    this.nextDrawAt,

    this.status = "ACTIVE",

    required this.creatorId,
    required this.creatorName,
    required this.createdAt,

    required this.progress,
    required this.themeColor,

    required this.numberOfWinners,
    required this.winnerIds,
    required this.winningTicketNumbers,

    this.resultMessage,
    this.drawCompletedAt,
  });

  // ==========================================
  // FIRESTORE → LOTTERY MODEL
  // ==========================================

  factory Lottery.fromFirestore(
    String id,
    Map<String, dynamic> data,
  ) {
    // ------------------------------
    // DRAW DATE
    // ------------------------------

    final Timestamp? nextDraw =
        data['nextDrawAt'] is Timestamp
            ? data['nextDrawAt'] as Timestamp
            : null;

    // ------------------------------
    // CREATED DATE
    // ------------------------------

    final Timestamp? created =
        data['createdAt'] is Timestamp
            ? data['createdAt'] as Timestamp
            : null;

    // ------------------------------
    // COMPLETED DATE
    // ------------------------------

    final Timestamp? completed =
        data['drawCompletedAt'] is Timestamp
            ? data['drawCompletedAt'] as Timestamp
            : null;

    // Your backend currently uses "drawnAt"
    final Timestamp? drawn =
        data['drawnAt'] is Timestamp
            ? data['drawnAt'] as Timestamp
            : null;

    // ------------------------------
    // TICKETS
    // ------------------------------

    final int sold =
        (data['ticketsSold'] as num?)?.toInt() ?? 0;

    final int total =
        (data['totalTickets'] as num?)?.toInt() ?? 0;

        final int remaining =
    (data['remainingTickets'] as num?)?.toInt() ??
    (total - sold).clamp(0, total);

    // ------------------------------
    // WINNER IDs
    // ------------------------------

    final List<String> winners =
        data['winnerIds'] != null
            ? List<String>.from(data['winnerIds'])
            : <String>[];

    // ------------------------------
    // WINNING TICKET NUMBERS
    // ------------------------------

    final List<int> winningTickets =
        data['winningTicketNumbers'] != null
            ? List<int>.from(
                (data['winningTicketNumbers'] as List)
                    .map(
                      (ticket) =>
                          (ticket as num).toInt(),
                    ),
              )
            : <int>[];

    // ------------------------------
    // RETURN LOTTERY
    // ------------------------------

    return Lottery(
      id: id,

      title:
          data['title'] ??
          'Untitled Lottery',

      description:
          data['description'] ??
          '',

      imageUrl:
          data['imageUrl'] as String?,

      jackpot:
          (data['jackpot'] as num?)
                  ?.toDouble() ??
              0,

      pricePerTicket:
          (data['pricePerTicket'] as num?)
                  ?.toDouble() ??
              0,

     totalTickets:
    total,

ticketsSold:
    sold,

remainingTickets:
    remaining,

maxTicketsPerUser:
          (data['maxTicketsPerUser'] as num?)
                  ?.toInt() ??
              1,

      category:
          data['category'] ??
          'Cash',

      cardStyle:
          data['cardStyle'] ??
          'Modern',

      lotteryType:
          data['lotteryType'] ??
          'oneTime',

      // IMPORTANT:
      // One-time lotteries can have null drawFrequency.
      drawFrequency:
          data['drawFrequency'] as String?,

      isPublic:
          data['isPublic'] ??
          true,

      // Some lotteries may not have nextDrawAt.
      nextDrawAt:
          nextDraw != null
              ? nextDraw.toDate()
              : null,

      status:
          data['status'] ??
          'ACTIVE',

      creatorId:
          data['creatorId'] ??
          '',

      creatorName:
          data['creatorName'] ??
          'Unknown Creator',

      createdAt:
          created != null
              ? created.toDate()
              : DateTime.now(),

      // ------------------------------
      // HOME CARD PROGRESS
      // ------------------------------

      progress:
          total > 0
              ? sold / total
              : 0,

      themeColor:
          (data['themeColor'] as num?)
                  ?.toInt() ??
              0xFF16A34A,

      // ------------------------------
      // DRAW RESULT
      // ------------------------------

      numberOfWinners:
          (data['numberOfWinners'] as num?)
                  ?.toInt() ??
              1,

      winnerIds:
          winners,

      winningTicketNumbers:
          winningTickets,

      resultMessage:
          data['resultMessage'] as String?,

      // Prefer drawnAt because that's what
      // your backend is currently returning.
      drawCompletedAt:
          drawn != null
              ? drawn.toDate()
              : completed != null
                  ? completed.toDate()
                  : null,
    );
  }

  // ==========================================
  // LOTTERY MODEL → FIRESTORE
  // ==========================================

  Map<String, dynamic> toMap(
    String userId,
  ) {
    return {
      "title":
          title,

      "description":
          description,

      "imageUrl":
          imageUrl,

      "jackpot":
          jackpot,

      "pricePerTicket":
          pricePerTicket,

      "totalTickets":
          totalTickets,

      "ticketsSold":
          ticketsSold,
          
          "remainingTickets":
    remainingTickets,


      "maxTicketsPerUser":
          maxTicketsPerUser,

      "category":
          category,

      "cardStyle":
          cardStyle,

      "lotteryType":
          lotteryType,

      "drawFrequency":
          drawFrequency,

      "isPublic":
          isPublic,

      "nextDrawAt":
          nextDrawAt,

      "status":
          status,

      "creatorId":
          userId,

      "creatorName":
          creatorName,

      "createdAt":
          createdAt,

      "progress":
          progress,

      "themeColor":
          themeColor,

      // ==============================
      // DRAW RESULT
      // ==============================

      "numberOfWinners":
          numberOfWinners,

      "winnerIds":
          winnerIds,

      "winningTicketNumbers":
          winningTicketNumbers,

      "resultMessage":
          resultMessage,

      "drawCompletedAt":
          drawCompletedAt,
    };
  }
}