// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcg-hrTX5BtGK39EvLcshnh5QokrCHPEc',
    appId: '1:408098838732:web:c284a9cb9eedb58d750a69',
    messagingSenderId: '408098838732',
    projectId: 'lottery-app-d7959',
    authDomain: 'lottery-app-d7959.firebaseapp.com',
    storageBucket: 'lottery-app-d7959.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6dWJ4GXfpsd39G9Of8JaXWHVQI-GzL4Y',
    appId: '1:408098838732:android:e7f30bc00de9f398750a69',
    messagingSenderId: '408098838732',
    projectId: 'lottery-app-d7959',
    storageBucket: 'lottery-app-d7959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd9IG4LZymHrYEYuuftv7qqxrhTfqbvk8',
    appId: '1:408098838732:ios:dad7d13f1ce42778750a69',
    messagingSenderId: '408098838732',
    projectId: 'lottery-app-d7959',
    storageBucket: 'lottery-app-d7959.firebasestorage.app',
    iosBundleId: 'com.example.luckyeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd9IG4LZymHrYEYuuftv7qqxrhTfqbvk8',
    appId: '1:408098838732:ios:dad7d13f1ce42778750a69',
    messagingSenderId: '408098838732',
    projectId: 'lottery-app-d7959',
    storageBucket: 'lottery-app-d7959.firebasestorage.app',
    iosBundleId: 'com.example.luckyeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcg-hrTX5BtGK39EvLcshnh5QokrCHPEc',
    appId: '1:408098838732:web:342e54f4fc9b52ac750a69',
    messagingSenderId: '408098838732',
    projectId: 'lottery-app-d7959',
    authDomain: 'lottery-app-d7959.firebaseapp.com',
    storageBucket: 'lottery-app-d7959.firebasestorage.app',
  );
}
